WITH TEMP (CYCLE_NUMBER, N, BATCH_DATE, WEEKS_IN_CYCLE) -- this is where you create a table for this data to land in, needs to have all your columns
AS 
(
    SELECT
    CD.CYCLE_NUMBER,
    0 AS N,-- create the number
    BS.BATCH_DATE AS BATCH_DATE,
    CD.WEEKS_IN_CYCLE
FROM 
    (SELECT 
    1 AS ONE,
    TO_DATE(NEXT_DAY ( SYSDATE-45, 'monday' ) + ( ( LEVEL - 1 ) * 7 )) BATCH_DATE
    FROM   DUAL
    CONNECT BY LEVEL <= 1) BS
LEFT JOIN (SELECT 1 AS ONE,C.* FROM ICHEM_DBA.BATCH_CYCLE_DETAILS C WHERE CYCLE_PURPOSE_ID = 81) CD ON (CD.ONE=BS.ONE)
  UNION ALL 
    SELECT 
    CYCLE_NUMBER, 
    N+1, 
(7*WEEKS_IN_CYCLE)+BATCH_DATE, 
    WEEKS_IN_CYCLE FROM TEMP
WHERE N < 500 AND BATCH_DATE<TO_DATE(SYSDATE + 120)
)
    SELECT * FROM TEMP 
    WHERE BATCH_DATE>=SYSDATE - 30
    AND BATCH_DATE<SYSDATE+120
